object_types = [
    'airport',
    'bareland',
    'baseball field',
    'beach',
    'bridge',
    'center',
    'church',
    'commercial',
    'dense residential',
    'desert',
    'farmland',
    'forest',
    'industrial',
    'meadow',
    'medium residential',
    'mountain',
    'park',
    'parking',
    'playground',
    'port',
    'railway station',
    'resort',
    'river',
    'school',
    'sparse residential',
    'square',
    'stadium',
    'storage tanks',
    'viaduct'
]